const actions = {
	SET_X: "SET_X",
	ADD_DIGIT: "ADD_DIGIT",
	EXCHANGE_X_WITH_Y: "EXCHANGE_X_WITH_Y",
	ROLE_DOWN: "ROLE_DOWN",
	ENTER: "ENTER",
	EXE_ARITHMETIC_OPERATOR: "EXE_ARITHMETIC_OPERATOR",
	EXE_NON_TRI_FUNCTION: "EXE_NON_TRI_FUNCTION",
	EXE_TRI_FUNCTION: "EXE_TRI_FUNCTION",
	X_POW_Y: "X_POW_Y",
	X_SQRT: "X_SQRT",
	REC: "REC",
	STO: "STO",
	MUL_INVERSE_X: "MUL_INVERSE_X",
	CLX: "CLX",
	CLR: "CLR",
	ADD_PI: "PI",
	CHS: "CHS",
	ADD_DOT: "ADD_DOT",
	ARC: "ARC",
	SHIFT_UP: "SHIFT_UP",
	ADD_EEX: "ADD_EEX",
	EXE_A_TRI_FUNCTION: "EXE_A_TRI_FUNCTION",
	ENABLE_ARC: "ENABLE_ARC"
};

export default actions;
